package examen1_alessandroreyes;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
public class Examen1_AlessandroReyes extends javax.swing.JFrame {
    
    /**
     * Creates new form Examen1_AlessandroReyes
     */
    public Examen1_AlessandroReyes() {
        initComponents();
        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setValue(1);
        nm.setMinimum(1);
        nm.setMaximum(5);
        js_puntaje.setModel(nm);
        js_puntaje2.setModel(nm);
        SpinnerNumberModel nm2 = new SpinnerNumberModel();
        nm2.setValue(1);
        nm2.setMinimum(1);
        js_copias.setModel(nm2);
        js_copias2.setModel(nm2);
        SpinnerNumberModel nm3 = new SpinnerNumberModel();
        nm3.setValue(1);
        nm3.setMinimum(1);
        js_edicion.setModel(nm3);
        js_edicion2.setModel(nm3);
        //-------------------------------------
        DefaultComboBoxModel modeloG = (DefaultComboBoxModel) cb_genero.getModel();
        modeloG.addElement(new Genero("Fantasía"));
        modeloG.addElement(new Genero("Romance"));
        modeloG.addElement(new Genero("Acción"));
        modeloG.addElement(new Genero("Historia"));
        cb_genero.setModel(modeloG);
        DefaultComboBoxModel modelom = (DefaultComboBoxModel) cb_genero2.getModel();
        modelom.addElement(new Genero("Fantasía"));
        modelom.addElement(new Genero("Romance"));
        modelom.addElement(new Genero("Acción"));
        modelom.addElement(new Genero("Historia"));
        cb_genero2.setModel(modelom);
        DefaultComboBoxModel modelonu = (DefaultComboBoxModel) cb_ngu.getModel();
        modelonu.addElement(new Genero("Fantasía"));
        modelonu.addElement(new Genero("Romance"));
        modelonu.addElement(new Genero("Acción"));
        modelonu.addElement(new Genero("Historia"));
        cb_ngu.setModel(modelonu);
        DefaultComboBoxModel mm = (DefaultComboBoxModel) cb_mod.getModel();
        mm.addElement("Titulo");
        mm.addElement("Autor");
        mm.addElement("Fecha");
        mm.addElement("Copias");
        mm.addElement("Edicion");
        mm.addElement("Puntaje");
        mm.addElement("Genero");
        mm.addElement("Precio");
        mm.addElement("Descripcion");
        cb_mod.setModel(mm);
        //------------------------------------------------------
        l_copias.setVisible(false);
        js_copias2.setVisible(false);
        l_descripcion.setVisible(false);
        tf_descripcion2.setVisible(false);
        l_edicion.setVisible(false);
        js_edicion2.setVisible(false);
        l_fecha.setVisible(false);
        dc_fecha2.setVisible(false);
        l_genero.setVisible(false);
        cb_genero2.setVisible(false);
        l_precio.setVisible(false);
        tf_precio2.setVisible(false);
        l_puntaje.setVisible(false);
        js_puntaje2.setVisible(false);
        l_titulo.setVisible(false);
        tf_titulo2.setVisible(false);
        l_autor.setVisible(false);
        tf_autor2.setVisible(false);
        //------------------------------------------------------
        tp.setEnabled(false);
        usuarios.add(admi);
        usuarios.add(User1);
        usuarios.add(User2);
        usuarios.add(User3);
        usuarios.add(User4);
        libros.add(libro1);
        libros.add(libro2);
        libros.add(libro3);
        libros.add(libro4);
        libros.add(libro5);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Crear_user = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_crearnu = new javax.swing.JButton();
        tf_nuser = new javax.swing.JTextField();
        tf_ncontra = new javax.swing.JTextField();
        tf_numtel = new javax.swing.JTextField();
        tf_nemail = new javax.swing.JTextField();
        cb_ngu = new javax.swing.JComboBox<>();
        dc_nnace = new com.toedter.calendar.JDateChooser();
        tp = new javax.swing.JTabbedPane();
        p_crear = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_titulo = new javax.swing.JTextField();
        tf_autor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        tf_descripcion = new javax.swing.JTextField();
        js_puntaje = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        js_copias = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        js_edicion = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        cb_genero = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tf_precio = new javax.swing.JTextField();
        btn_crearlibro = new javax.swing.JButton();
        p_modificar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tf_mod = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cb_mod = new javax.swing.JComboBox<>();
        btn_continue = new javax.swing.JButton();
        l_titulo = new javax.swing.JLabel();
        l_descripcion = new javax.swing.JLabel();
        l_autor = new javax.swing.JLabel();
        l_fecha = new javax.swing.JLabel();
        l_puntaje = new javax.swing.JLabel();
        tf_titulo2 = new javax.swing.JTextField();
        tf_autor2 = new javax.swing.JTextField();
        tf_descripcion2 = new javax.swing.JTextField();
        l_copias = new javax.swing.JLabel();
        js_puntaje2 = new javax.swing.JSpinner();
        js_copias2 = new javax.swing.JSpinner();
        l_edicion = new javax.swing.JLabel();
        js_edicion2 = new javax.swing.JSpinner();
        l_genero = new javax.swing.JLabel();
        cb_genero2 = new javax.swing.JComboBox<>();
        dc_fecha2 = new com.toedter.calendar.JDateChooser();
        l_precio = new javax.swing.JLabel();
        tf_precio2 = new javax.swing.JTextField();
        btn_modificar = new javax.swing.JButton();
        p_otras = new javax.swing.JPanel();
        p_fav = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_lista = new javax.swing.JTextArea();
        p_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_contraseña = new javax.swing.JTextField();
        bt_login = new javax.swing.JButton();

        jLabel14.setText("Ingrese su usuario");

        jLabel15.setText("Ingrese la contraseña");

        jLabel16.setText("Ingrese su Fecha de nacimiento");

        jLabel17.setText("Ingrese su numoer de telefono");

        jLabel18.setText("ingrese su email");

        jLabel19.setText("Ingrese su genero favorito");

        btn_crearnu.setText("Crear");
        btn_crearnu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearnuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Crear_userLayout = new javax.swing.GroupLayout(Crear_user.getContentPane());
        Crear_user.getContentPane().setLayout(Crear_userLayout);
        Crear_userLayout.setHorizontalGroup(
            Crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_userLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Crear_userLayout.createSequentialGroup()
                        .addGroup(Crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Crear_userLayout.createSequentialGroup()
                        .addGroup(Crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Crear_userLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Crear_userLayout.createSequentialGroup()
                                .addComponent(tf_numtel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addGap(274, 274, 274)))
                        .addComponent(btn_crearnu)
                        .addGap(111, 111, 111))
                    .addGroup(Crear_userLayout.createSequentialGroup()
                        .addGroup(Crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb_ngu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_nuser, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(tf_ncontra)
                                .addComponent(tf_nemail))
                            .addComponent(dc_nnace, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Crear_userLayout.setVerticalGroup(
            Crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_userLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_nuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel15)
                .addGap(13, 13, 13)
                .addComponent(tf_ncontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(13, 13, 13)
                .addComponent(dc_nnace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Crear_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Crear_userLayout.createSequentialGroup()
                        .addComponent(tf_numtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(tf_nemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Crear_userLayout.createSequentialGroup()
                        .addComponent(btn_crearnu)
                        .addGap(54, 54, 54)))
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(cb_ngu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Titulo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Autor");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Descripcion");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Fecha");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Puntaje");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Copias");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Edición");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Genero");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Precio");

        btn_crearlibro.setText("Crear Libro");
        btn_crearlibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearlibroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_crearLayout = new javax.swing.GroupLayout(p_crear);
        p_crear.setLayout(p_crearLayout);
        p_crearLayout.setHorizontalGroup(
            p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_crearLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_crearLayout.createSequentialGroup()
                        .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addGroup(p_crearLayout.createSequentialGroup()
                                .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(tf_titulo)
                                    .addComponent(jLabel5)
                                    .addComponent(tf_descripcion)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_crearLayout.createSequentialGroup()
                                        .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_crearLayout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18))
                                            .addGroup(p_crearLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(26, 26, 26)))
                                        .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(js_puntaje, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                            .addComponent(js_copias))
                                        .addGap(102, 102, 102)))
                                .addGap(80, 80, 80)
                                .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(tf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(p_crearLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(js_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addGroup(p_crearLayout.createSequentialGroup()
                        .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_crearlibro)
                        .addGap(179, 179, 179))))
        );
        p_crearLayout.setVerticalGroup(
            p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_crearLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(tf_autor))
                .addGap(30, 30, 30)
                .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(js_puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(js_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(js_copias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_crearLayout.createSequentialGroup()
                        .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_crearLayout.createSequentialGroup()
                        .addComponent(btn_crearlibro)
                        .addGap(10, 10, 10)))
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        tp.addTab("Crear libros", p_crear);

        jLabel12.setText("Titulo del libro que desea modificar");

        jLabel13.setText("Que desea modificar del libro");

        btn_continue.setText("Continue");
        btn_continue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_continueMouseClicked(evt);
            }
        });

        l_titulo.setText("Titulo");

        l_descripcion.setText("Descripcion");

        l_autor.setText("Autor");

        l_fecha.setText("Fecha");

        l_puntaje.setText("Puntaje");

        l_copias.setText("Copias");

        l_edicion.setText("Edicion");

        l_genero.setText("Genero");

        l_precio.setText("Precio");

        btn_modificar.setText("Modificar");
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_modificarLayout = new javax.swing.GroupLayout(p_modificar);
        p_modificar.setLayout(p_modificarLayout);
        p_modificarLayout.setHorizontalGroup(
            p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_modificarLayout.createSequentialGroup()
                .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_modificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(l_genero)
                        .addGap(224, 224, 224)
                        .addComponent(l_precio))
                    .addGroup(p_modificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_modificarLayout.createSequentialGroup()
                                .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_mod)
                                        .addComponent(jLabel12)
                                        .addComponent(l_titulo)
                                        .addComponent(l_descripcion)
                                        .addComponent(tf_descripcion2)
                                        .addComponent(tf_titulo2))
                                    .addComponent(cb_genero2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p_modificarLayout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(l_fecha)
                                            .addComponent(l_autor)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cb_mod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tf_autor2)
                                            .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_modificarLayout.createSequentialGroup()
                                                    .addComponent(l_edicion)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(js_edicion2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(dc_fecha2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(p_modificarLayout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(tf_precio2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_modificarLayout.createSequentialGroup()
                                    .addComponent(l_copias)
                                    .addGap(18, 18, 18)
                                    .addComponent(js_copias2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_modificarLayout.createSequentialGroup()
                                    .addComponent(l_puntaje)
                                    .addGap(18, 18, 18)
                                    .addComponent(js_puntaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(p_modificarLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_modificar)
                            .addComponent(btn_continue))))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        p_modificarLayout.setVerticalGroup(
            p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_modificarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_continue)
                .addGap(18, 18, 18)
                .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_modificarLayout.createSequentialGroup()
                        .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_titulo)
                            .addComponent(l_autor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_autor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_descripcion)
                            .addComponent(l_fecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_descripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dc_fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_puntaje)
                    .addComponent(js_puntaje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_edicion)
                    .addComponent(js_edicion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_copias)
                    .addComponent(js_copias2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_genero)
                    .addComponent(l_precio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_genero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_precio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btn_modificar))
        );

        tp.addTab("Modificar libros", p_modificar);

        javax.swing.GroupLayout p_otrasLayout = new javax.swing.GroupLayout(p_otras);
        p_otras.setLayout(p_otrasLayout);
        p_otrasLayout.setHorizontalGroup(
            p_otrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        p_otrasLayout.setVerticalGroup(
            p_otrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        tp.addTab("Otras acciones", p_otras);

        ta_lista.setColumns(20);
        ta_lista.setRows(5);
        jScrollPane1.setViewportView(ta_lista);

        javax.swing.GroupLayout p_favLayout = new javax.swing.GroupLayout(p_fav);
        p_fav.setLayout(p_favLayout);
        p_favLayout.setHorizontalGroup(
            p_favLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_favLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        p_favLayout.setVerticalGroup(
            p_favLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_favLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        tp.addTab("Libros por genero favorito", p_fav);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Contraseña");

        bt_login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_login.setText("Log in");
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout p_loginLayout = new javax.swing.GroupLayout(p_login);
        p_login.setLayout(p_loginLayout);
        p_loginLayout.setHorizontalGroup(
            p_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_loginLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_loginLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_usuario)
                    .addComponent(tf_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_loginLayout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(bt_login)
                .addGap(297, 297, 297))
        );
        p_loginLayout.setVerticalGroup(
            p_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_loginLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(bt_login)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        tp.addTab("Log in", p_login);

        tp.setSelectedComponent(p_login);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp)
                .addContainerGap())
        );

        tp.getAccessibleContext().setAccessibleParent(p_login);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseClicked
        boolean t = false;
        for (int i = 0; i < usuarios.size(); i++) {
            if(usuarios.get(i).getN_usuario().equals(tf_usuario.getText()) &&
                    usuarios.get(i).getContraseña().equals(tf_contraseña.getText())){
                t = true;
                user = i;
            }
        }
        if(t == false){
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta");
            Crear_user.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Ha ingresado con exito");
            tp.setEnabled(true);
            tf_usuario.setText("");
            tf_contraseña.setText("");
        }
    }//GEN-LAST:event_bt_loginMouseClicked

    private void btn_crearlibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearlibroMouseClicked
        try {
            Libro l = new Libro(tf_titulo.getText(), tf_descripcion.getText(), (Integer) js_puntaje.getValue(),
                    (Integer) js_copias.getValue(), cb_genero.getSelectedItem().toString(),
                    Integer.parseInt(tf_precio.getText()), (Integer) js_edicion.getValue(), tf_autor.getText(),
                    dc_fecha.getDate());
            l.setAutor((tf_autor.getText()));
            libros.add(l);
            JOptionPane.showMessageDialog(this, "Libro guardado exitosamente");
            SpinnerNumberModel nm = new SpinnerNumberModel();
            nm.setValue(1);
            nm.setMinimum(1);
            nm.setMaximum(5);
            js_puntaje.setModel(nm);
            SpinnerNumberModel nm2 = new SpinnerNumberModel();
            nm2.setValue(1);
            nm2.setMinimum(1);
            js_copias.setModel(nm2);
            SpinnerNumberModel nm3 = new SpinnerNumberModel();
            nm3.setValue(1);
            nm3.setMinimum(1);
            js_edicion.setModel(nm3);
            tf_titulo.setText("");
            tf_descripcion.setText("");
            tf_precio.setText("");
            tf_autor.setText("");
            dc_fecha.setDate(new Date());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Oucrrio un error y no se guardaron los datos");
        }

    }//GEN-LAST:event_btn_crearlibroMouseClicked

    private void btn_continueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_continueMouseClicked
        if (cb_mod.getSelectedItem().toString().equals("Titulo")) {
            l_titulo.setVisible(true);
            tf_titulo2.setVisible(true);
        } else if (cb_mod.getSelectedItem().toString().equals("Autor")) {
            l_autor.setVisible(true);
            tf_autor2.setVisible(true);
        } else if (cb_mod.getSelectedItem().toString().equals("Fecha")) {
            l_fecha.setVisible(true);
            dc_fecha2.setVisible(true);
        } else if (cb_mod.getSelectedItem().toString().equals("Copias")) {
            l_copias.setVisible(true);
            js_copias2.setVisible(true);
        } else if (cb_mod.getSelectedItem().toString().equals("Edicion")) {
            l_edicion.setVisible(true);
            js_edicion2.setVisible(true);
        } else if (cb_mod.getSelectedItem().toString().equals("Puntaje")) {
            l_puntaje.setVisible(true);
            js_puntaje2.setVisible(true);
        } else if (cb_mod.getSelectedItem().toString().equals("Genero")) {
            l_genero.setVisible(true);
            cb_genero2.setVisible(true);
        } else if (cb_mod.getSelectedItem().toString().equals("Precio")) {
            l_precio.setVisible(true);
            tf_precio2.setVisible(true);
        } else if (cb_mod.getSelectedItem().toString().equals("Descripcion")) {
            l_descripcion.setVisible(true);
            tf_descripcion2.setVisible(true);
        }
    }//GEN-LAST:event_btn_continueMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        int pos = 0;
        for (int i = 0; i < libros.size(); i++) {
            if (libros.get(i).getTitulo().equals(tf_mod.getText())) {
                pos = i;
            }
        }
        if (cb_mod.getSelectedItem().toString().equals("Titulo")) {
            libros.get(pos).setTitulo(tf_titulo2.getText());
        } else if (cb_mod.getSelectedItem().toString().equals("Autor")) {
            libros.get(pos).setAutor(tf_autor2.getText());
        } else if (cb_mod.getSelectedItem().toString().equals("Fecha")) {
            libros.get(pos).setPublish(dc_fecha2.getDate());
        } else if (cb_mod.getSelectedItem().toString().equals("Copias")) {
            libros.get(pos).setCopias((Integer) js_copias2.getValue());
        } else if (cb_mod.getSelectedItem().toString().equals("Edicion")) {
            libros.get(pos).setEdicion((Integer) js_edicion2.getValue());
        } else if (cb_mod.getSelectedItem().toString().equals("Puntaje")) {
            libros.get(pos).setPuntaje((Integer) js_puntaje2.getValue());
        } else if (cb_mod.getSelectedItem().toString().equals("Genero")) {
            libros.get(pos).setGenero(cb_genero2.getSelectedItem().toString());
        } else if (cb_mod.getSelectedItem().toString().equals("Precio")) {
            libros.get(pos).setValor(Integer.parseInt(tf_precio2.getText()));
        } else if (cb_mod.getSelectedItem().toString().equals("Descripcion")) {
            libros.get(pos).setDescripcion(tf_descripcion2.getText());
        }
        l_copias.setVisible(false);
        js_copias2.setVisible(false);
        l_descripcion.setVisible(false);
        tf_descripcion2.setVisible(false);
        l_edicion.setVisible(false);
        js_edicion2.setVisible(false);
        l_fecha.setVisible(false);
        dc_fecha2.setVisible(false);
        l_genero.setVisible(false);
        cb_genero2.setVisible(false);
        l_precio.setVisible(false);
        tf_precio2.setVisible(false);
        l_puntaje.setVisible(false);
        js_puntaje2.setVisible(false);
        l_titulo.setVisible(false);
        tf_titulo2.setVisible(false);
        l_autor.setVisible(false);
        tf_autor2.setVisible(false);
        tf_mod.setText("");
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void btn_crearnuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearnuMouseClicked
        try {
            Usuario U = new Usuario(tf_nuser.getText(), tf_ncontra.getText(), dc_nnace.getDate(),
                    Integer.parseInt(tf_numtel.getText()), tf_nemail.getText(), cb_ngu.getSelectedItem().toString());
            usuarios.add(U);
            JOptionPane.showMessageDialog(this, "Usuario creado Exitosamente");
            Crear_user.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Oucrrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_btn_crearnuMouseClicked

    private void tpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpStateChanged
        if(tp.getSelectedIndex()==3){
            ta_lista.setText("");
            for (int i = 0; i < libros.size(); i++) {
                if(libros.get(i).getGenero() == usuarios.get(user).getGen_fav())
                    ta_lista.append(libros.get(i).getTitulo()+"\n");
            }
        }
    }//GEN-LAST:event_tpStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen1_AlessandroReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen1_AlessandroReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen1_AlessandroReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen1_AlessandroReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen1_AlessandroReyes().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Crear_user;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton btn_continue;
    private javax.swing.JButton btn_crearlibro;
    private javax.swing.JButton btn_crearnu;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JComboBox<String> cb_genero2;
    private javax.swing.JComboBox<String> cb_mod;
    private javax.swing.JComboBox<String> cb_ngu;
    private com.toedter.calendar.JDateChooser dc_fecha;
    private com.toedter.calendar.JDateChooser dc_fecha2;
    private com.toedter.calendar.JDateChooser dc_nnace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner js_copias;
    private javax.swing.JSpinner js_copias2;
    private javax.swing.JSpinner js_edicion;
    private javax.swing.JSpinner js_edicion2;
    private javax.swing.JSpinner js_puntaje;
    private javax.swing.JSpinner js_puntaje2;
    private javax.swing.JLabel l_autor;
    private javax.swing.JLabel l_copias;
    private javax.swing.JLabel l_descripcion;
    private javax.swing.JLabel l_edicion;
    private javax.swing.JLabel l_fecha;
    private javax.swing.JLabel l_genero;
    private javax.swing.JLabel l_precio;
    private javax.swing.JLabel l_puntaje;
    private javax.swing.JLabel l_titulo;
    private javax.swing.JPanel p_crear;
    private javax.swing.JPanel p_fav;
    private javax.swing.JPanel p_login;
    private javax.swing.JPanel p_modificar;
    private javax.swing.JPanel p_otras;
    private javax.swing.JTextArea ta_lista;
    private javax.swing.JTextField tf_autor;
    private javax.swing.JTextField tf_autor2;
    private javax.swing.JTextField tf_contraseña;
    private javax.swing.JTextField tf_descripcion;
    private javax.swing.JTextField tf_descripcion2;
    private javax.swing.JTextField tf_mod;
    private javax.swing.JTextField tf_ncontra;
    private javax.swing.JTextField tf_nemail;
    private javax.swing.JTextField tf_numtel;
    private javax.swing.JTextField tf_nuser;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_precio2;
    private javax.swing.JTextField tf_titulo;
    private javax.swing.JTextField tf_titulo2;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTabbedPane tp;
    // End of variables declaration//GEN-END:variables
    ArrayList <Usuario> usuarios = new ArrayList();
    int user;
    Usuario admi = new Usuario("admi", "1234");
    Usuario User1 = new Usuario("user1", "1234");
    Usuario User2 = new Usuario("user2", "1234");
    Usuario User3 = new Usuario("user3", "1234");
    Usuario User4 = new Usuario("user4", "1234");
    ArrayList <Libro> libros = new ArrayList();
    Libro libro1 = new Libro("Cruzando el parque", "De un niño abandonado", 2, 100, 
            "Romance", 990, 1, "Alessandro");
    Libro libro2 = new Libro("Cruzando el lago", "De una niña abandonado", 2, 100, 
            "Romance", 990, 1, "Reyes");
    Libro libro3 = new Libro("Narcos", "Unos presidentes en apuros", 5, 100, 
            "Accion", 1990, 1, "Trimarchi");
    Libro libro4 = new Libro("Iron Maiden", "Historia de una banda", 2, 100, 
            "HIstoria", 990, 1, "Alessandro");
    Libro libro5 = new Libro("El Principe", "De un niño afortunado", 2, 100, 
            "Fantasia", 990, 1, "Gabriel");
}
